---
title: "analyze"
output: html_document
date: '2022-08-01'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load data

```{r}
df <- read.csv("../output/combined_megafile.csv")

library(tidyverse)
teamdf <- df %>% 
  group_by(team) %>% 
  summarize(
    effort = sum(process_effort_s),
    skill_use = sum(process_skill_use_s),
    strategy = sum(process_workload_burnt),
    comms_words = sum(comms_total_words),
    comms_eq = sum(comms_equity),
    score = sum(team_score),
    critical_victims = sum(critic_victim),
    mark_skill_mean = mean(team_marking_skill_mean),
    mark_skill_sd = mean(team_marking_skill_sd),
    transport_skill_mean = mean(team_transporting_skill_mean),
    transport_skill_sd = mean(team_transporting_skill_sd),
    walk_skill_mean = mean(team_walking_skill_mean),
    walk_skill_sd = mean(team_walking_skill_sd),
    sbsod_mean = mean(team_sbsod_mean),
    sbsod_sd = mean(team_sbsod_sd),
    anxiety_mean = mean(team_anxiety_mean),
    anxiety_sd = mean(team_anxiety_sd),
    anger_mean = mean(team_anger_mean),
    anger_sd = mean(team_anger_sd),
    gaming_experience_mean = mean(team_gaming_experience_mean),
    gaming_experience_sd = mean(team_gaming_experience_sd),
    mission_knowledge_mean = mean(team_mission_knowledge_mean),
    mission_knowledge_sd = mean(team_mission_knowledge_sd)
  )
```

# Hypothesis 1

```{r}

summary(lm(score ~ mission_knowledge_mean + mission_knowledge_sd + 
                   transport_skill_mean + transport_skill_sd + 
                   mark_skill_mean + mark_skill_sd + walk_skill_mean + walk_skill_sd +
                   gaming_experience_mean + gaming_experience_sd +
                   anger_mean + anger_sd +
                   anxiety_mean + anxiety_sd + 
                   sbsod_mean + sbsod_sd,
           data = teamdf))

summary(lm(critical_victims ~ mission_knowledge_mean + mission_knowledge_sd + 
                   transport_skill_mean + transport_skill_sd + 
                   mark_skill_mean + mark_skill_sd + walk_skill_mean + walk_skill_sd +
                   gaming_experience_mean + gaming_experience_sd +
                   anger_mean + anger_sd +
                   anxiety_mean + anxiety_sd + 
                   sbsod_mean + sbsod_sd,
           data = teamdf))

```


# Hypothesis 2

```{r}

intdf <- teamdf %>% 
  mutate(anxsquared = anxiety_mean * anxiety_mean)

summary(lm(score ~ mission_knowledge_mean + mission_knowledge_sd + 
                   transport_skill_mean + transport_skill_sd + 
                   mark_skill_mean + mark_skill_sd + walk_skill_mean + walk_skill_sd +
                   gaming_experience_mean + gaming_experience_sd +
                   anger_mean + anger_sd +
                   anxiety_mean + anxiety_sd + anxsquared +
                   sbsod_mean + sbsod_sd,
           data = intdf))

summary(lm(critical_victims ~ mission_knowledge_mean + mission_knowledge_sd + 
                   transport_skill_mean + transport_skill_sd + 
                   mark_skill_mean + mark_skill_sd + walk_skill_mean + walk_skill_sd +
                   gaming_experience_mean + gaming_experience_sd +
                   anger_mean + anger_sd +
                   anxiety_mean + anxiety_sd + anxsquared + 
                   sbsod_mean + sbsod_sd,
           data = intdf))

```

# Hypothesis 3

```{r}

summary(lm(effort ~ mission_knowledge_mean + mission_knowledge_sd + 
                   transport_skill_mean + transport_skill_sd + 
                   mark_skill_mean + mark_skill_sd + walk_skill_mean + walk_skill_sd +
                   gaming_experience_mean + gaming_experience_sd +
                   anger_mean + anger_sd +
                   anxiety_mean + anxiety_sd + 
                   sbsod_mean + sbsod_sd,
           data = teamdf))

summary(lm(skill_use ~ mission_knowledge_mean + mission_knowledge_sd + 
                   transport_skill_mean + transport_skill_sd + 
                   mark_skill_mean + mark_skill_sd + walk_skill_mean + walk_skill_sd +
                   gaming_experience_mean + gaming_experience_sd +
                   anger_mean + anger_sd +
                   anxiety_mean + anxiety_sd + 
                   sbsod_mean + sbsod_sd,
           data = teamdf))

summary(lm(strategy ~ mission_knowledge_mean + mission_knowledge_sd + 
                   transport_skill_mean + transport_skill_sd + 
                   mark_skill_mean + mark_skill_sd + walk_skill_mean + walk_skill_sd +
                   gaming_experience_mean + gaming_experience_sd +
                   anger_mean + anger_sd +
                   anxiety_mean + anxiety_sd + 
                   sbsod_mean + sbsod_sd,
           data = teamdf))


```

# Hypothesis 4

```{r}


summary(lm(effort ~ mission_knowledge_mean + mission_knowledge_sd + 
                   transport_skill_mean + transport_skill_sd + 
                   mark_skill_mean + mark_skill_sd + walk_skill_mean + walk_skill_sd +
                   gaming_experience_mean + gaming_experience_sd +
                   anger_mean + anger_sd +
                   anxiety_mean + anxiety_sd + 
                   sbsod_mean + sbsod_sd,
           data = teamdf))

summary(lm(skill_use ~ mission_knowledge_mean + mission_knowledge_sd + 
                   transport_skill_mean + transport_skill_sd + 
                   mark_skill_mean + mark_skill_sd + walk_skill_mean + walk_skill_sd +
                   gaming_experience_mean + gaming_experience_sd +
                   anger_mean + anger_sd +
                   anxiety_mean + anxiety_sd + 
                   sbsod_mean + sbsod_sd,
           data = teamdf))

summary(lm(strategy ~ mission_knowledge_mean + mission_knowledge_sd + 
                   transport_skill_mean + transport_skill_sd + 
                   mark_skill_mean + mark_skill_sd + walk_skill_mean + walk_skill_sd +
                   gaming_experience_mean + gaming_experience_sd +
                   anger_mean + anger_sd +
                   anxiety_mean + anxiety_sd + 
                   sbsod_mean + sbsod_sd,
           data = teamdf))

```

# Hypothesis 5

```{r}

hy5int <- teamdf %>% 
  mutate(int_skillanx = anxiety_mean*walk_skill_mean)

summary(lm(effort ~ mission_knowledge_mean + mission_knowledge_sd + 
                   transport_skill_mean + transport_skill_sd + 
                   mark_skill_mean + mark_skill_sd + walk_skill_mean + walk_skill_sd +
                   gaming_experience_mean + gaming_experience_sd +
                   anger_mean + anger_sd +
                   anxiety_mean + anxiety_sd + 
                   sbsod_mean + sbsod_sd,
           data = teamdf))

summary(lm(skill_use ~ mission_knowledge_mean + mission_knowledge_sd + 
                   transport_skill_mean + transport_skill_sd + 
                   mark_skill_mean + mark_skill_sd + walk_skill_mean + walk_skill_sd +
                   gaming_experience_mean + gaming_experience_sd +
                   anger_mean + anger_sd +
                   anxiety_mean + anxiety_sd + 
                   sbsod_mean + sbsod_sd,
           data = teamdf))

summary(lm(strategy ~ mission_knowledge_mean + mission_knowledge_sd + 
                   transport_skill_mean + transport_skill_sd + 
                   mark_skill_mean + mark_skill_sd + walk_skill_mean + walk_skill_sd +
                   gaming_experience_mean + gaming_experience_sd +
                   anger_mean + anger_sd +
                   anxiety_mean + anxiety_sd + 
                   sbsod_mean + sbsod_sd,
           data = teamdf))

```

# Hypothesis 6

```{r}

summary(lm(score ~ effort + strategy + skill_use,
           data = teamdf))

```

# Hypothesis 7

To do

# Hypothesis 8

```{r}

summary(lm(score ~ comms_words,
           data = teamdf))

summary(lm(score ~ comms_eq,
           data = teamdf))

summary(lm(critical_victims ~ comms_words,
           data = teamdf))

summary(lm(critical_victims ~ comms_eq,
           data = teamdf))


summary(lm(skill_use ~ comms_words,
           data = teamdf))

summary(lm(skill_use ~ comms_eq,
           data = teamdf))

```













